- hosts: all
  become: yes

  handlers:
    - name: yum update
      yum:
        name: '*'
        state: latest
    
    - name: restart Apache
      service: name=httpd state=restarted

  tasks:
    - name: Install git client
      yum: name=git state=present

    - name: Download and deploy Rapid
      git:
        repo: https://github.com/dcfield/swift
        dest: /var/www/html/CodeIgniter-3.1.5/
        clone: yes

    - name: Install apache web server
      yum: name=httpd state=present

    - name: Ensure apache started and enabled
      service: name=httpd state=started enabled=yes

    - name: Add EPEL repo
      yum:
        name: https://mirrors.nic.cz/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm
        state: present

    - name: Add Webtatic method
      yum:
        name: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
        state: present

    - name: Add webtatic repo
      yum:
        name: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
        state: present

    - name: Install php7 & required packages
      yum: name={{ item }} state=present
      with_items:
        - mod_php71w
        - php71w-cli
        - php71w-common
        - php71w-gd
        - php71w-mbstring
        - php71w-mcrypt
        - php71w-mysqlnd
        - php71w-xml
        - unzip
        - vim
        - mariadb

    - name: Change the files ownership to be owned by vagrant
      file:
        path: /var/www/html
        owner: vagrant
        group: vagrant
        recurse: yes

    - name: Change home web directory to point to /var/www/html/CodeIgniter-3.x.x
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^.*DocumentRoot "/var/www/html".*$'
        line: DocumentRoot "/var/www/html/CodeIgniter-3.1.5"
        state: present
      notify:
        - restart Apache

    - name: Ensure mod_rewrite is enabled in apache
      lineinfile:
        path: /etc/httpd/conf.modules.d/00-base.conf
        regexp: '^.*rewrite_module.*$'
        line: 'LoadModule rewrite_module modules/mod_rewrite.so'
        state: present

    - name: Copy htaccess to CodeIgniter
      copy:
        src: htaccess
        dest: /var/www/html/CodeIgniter-3.1.5/.htaccess
        owner: vagrant
        group: vagrant

    - name: Allow .htaccess file to be used
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        insertafter: '</Directory>'
        line: |
          <Directory "/var/www/html/CodeIgniter-3.1.5">
            AllowOverride all
          </Directory>
      notify:
        - restart Apache
        
    - name: Upload database.php file
      copy:
        src: database.php
        dest: /var/www/html/CodeIgniter-3.1.5/application/config/database.php 
        owner: vagrant
        group: vagrant

