- hosts: all
  become: yes

  tasks:
    - name: Ensure MariaDB is installed
      yum: name='{{ item }}' state=present
      with_items:
        - mariadb-server
        - MySQL-python

    - name: Ensure MariaDB is started and enabled
      service: name=mariadb state=started enabled=yes

    - name: Set the root password for mysql
      mysql_user:
        name: root
        password: admin
        state: present

    - name: Upload the .my.cnf file to save the credentials
      copy:
        src: my.cnf
        dest: /root/.my.cnf
        owner: root 
        mode: 0600

    - name: Remove anonymous account
      mysql_user:
        name: ''
        host_all: yes
        state: absent

    - name: Create app db
      mysql_db: 
        name: ci_database
        state: present

    - name: Create app user
      mysql_user:
        name: ci_user
        password: cipassword
        host: '%'
        priv: ci_database.*:ALL
        state: present

    - name: Upload booking.sql
      copy:
        src: booking.sql
        dest: /tmp/booking.sql
        
    - name: Import booking.sql
      mysql_db:
        state: import
        name: all
        target: /tmp/booking.sql
